version: "3.1"

services:
  db:
    container_name: database
    image: sameersbn/postgresql:10-2
    environment:
      PG_PASSWORD: $DB_PASS
    env_file:
      - ".env"
    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./pg_data:/var/lib/postgresql/

  ruanbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"
    depends_on:
      - db
    volumes:
    - .:/src/

networks:
  botnet:
    driver: bridge